#include "shaders.h"

const char *baseVertexShader =
    "#version 330\n"
    "\n"
    "// Input vertex attributes\n"
    "in vec3 vertexPosition;\n"
    "in vec2 vertexTexCoord;\n"
    "in vec3 vertexNormal;\n"
    "in vec4 vertexColor;\n"
    "\n"
    "// Input uniform values\n"
    "uniform mat4 mvp;\n"
    "\n"
    "// Output vertex attributes (to fragment shader)\n"
    "out vec2 fragTexCoord;\n"
    "out vec4 fragColor;\n"
    "\n"
    "// NOTE: Add your custom variables here\n"
    "\n"
    "void main()\n"
    "{\n"
    "    // Send vertex attributes to fragment shader\n"
    "    fragTexCoord = vertexTexCoord;\n"
    "    fragColor = vertexColor;\n"
    "\n"
    "    // Calculate final vertex position\n"
    "    gl_Position = mvp*vec4(vertexPosition, 1.0);\n"
    "}"
;

const char *pixelizerFragmentShader = 
    "#version 330\n"
    "\n"
    "// Input vertex attributes (from vertex shader)\n"
    "in vec2 fragTexCoord;\n"
    "in vec4 fragColor;\n"
    "\n"
    "// Input uniform values\n"
    "uniform sampler2D texture0;\n"
    "uniform vec4 colDiffuse;\n"
    "\n"
    "// Output fragment color\n"
    "out vec4 finalColor;\n"
    "\n"
    "// NOTE: Add your custom variables here\n"
    "\n"
    "// NOTE: Render size values must be passed from code\n"
    "uniform int renderWidth = 800;\n"
    "uniform int renderHeight = 600;\n"
    "\n"
    "uniform float pixelWidth = 3.0;\n"
    "uniform float pixelHeight = 3.0;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    float dx = pixelWidth*(1.0/renderWidth);\n"
    "    float dy = pixelHeight*(1.0/renderHeight);\n"
    "\n"
    "    vec2 coord = vec2(dx*floor(fragTexCoord.x/dx), dy*floor(fragTexCoord.y/dy));\n"
    "\n"
    "    vec3 tc = texture(texture0, coord).rgb;\n"
    "\n"
    "    finalColor = vec4(tc, 1.0);\n"
    "}"
;